#! /usr/bin/env python3
""" docstring """


import argparse
import os
import dcatools as tools


def parse_options():
    """cli parser"""
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-i", "--input", dest="input", required=True, help="mat file"
    )
    return parser.parse_args()


def main():
    """do stuff"""
    options = parse_options()
    prefix = os.path.splitext((options.input).replace("/", "_"))[0]

    alignment, h, J = tools.load_model_mat(options.input)
    M = alignment.shape[0]
    Q, N = h.shape

    alignment_file = prefix + "_msa_numerical.txt"
    tools.save_alignment((alignment - 1), M, N, Q, alignment_file)

    parameters_file = prefix + "_parameters.txt"
    tools.save_parameters(h, J, M, N, Q, parameters_file)


if __name__ == "__main__":
    main()
