#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2020 - 2023 sudorook <daemon@nullcodon.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

""" docstring """


import argparse
import os
import dcatools as tools


def parse_options():
    """cli parser"""
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-i", "--input", dest="input", required=True, help="mat file"
    )
    return parser.parse_args()


def main():
    """do stuff"""
    options = parse_options()
    prefix = os.path.splitext((options.input).replace("/", "_"))[0]

    alignment, h, J = tools.load_model_mat(options.input)
    M = alignment.shape[0]
    Q, N = h.shape

    alignment_file = prefix + "_msa_numerical.txt"
    tools.save_alignment((alignment - 1), M, N, Q, alignment_file)

    parameters_file = prefix + "_parameters.txt"
    tools.save_parameters(h, J, M, N, Q, parameters_file)


if __name__ == "__main__":
    main()
