#! /bin/bash
set -eu

function make_figures() {
  local name="$1"
  local description="$2"
  local title="$name, $description"

  local slug
  slug="$(echo "$description" | \
          sed -r s/λ/l/g | \
          sed -r s/α/a/g | \
          iconv -t ascii//TRANSLIT | \
          sed -r s/[~\^]+//g | \
          sed -r s/[^a-zA-Z0-9]+/_/g | \
          sed -r s/^-+\|-+$//g | tr A-Z a-z)"

  local step="$3"
  local nproc="$4"

  export OMP_NUM_THREADS="$nproc"

  local cpulist=0
  for i in $(seq 2 1 "$nproc"); do
    cpulist="${cpulist},${i}"
  done

  local prev_step
  for i in $(ls -t stat_MC_2p_[0-9]*.bin | \
               cut -d "_" -f4 | cut -d"." -f1); do
    if [[ "$i" -lt "$step" ]]; then
      prev_step="$i"
      break
    fi
  done

  echo "run log"
  plot_runlog -i bmdca_run.log -o "${name}_${slug}_runlog.png"
  echo

  echo "stats comparison"
  plot_msa_compare \
    -n msa_numerical.txt \
    -w sequence_weights.txt \
    -N "MC_samples_${step}.txt" \
    -l "MSA" \
    -L "MC" \
    -T "${title}, step ${step}" -p 3 -c

  echo "pca projection"
  taskset --cpu-list "$cpulist" plot_msa_proj \
    -n msa_numerical.txt \
    -w sequence_weights.txt \
    -N "MC_samples_${step}.txt" \
    -t "${title}, step ${step}" \
    -o "${name}_${slug}_proj_${step}.png"
  echo

  echo "sequence energies"
  compute_energies \
    -n msa_numerical.txt \
    -p "parameters_h_${step}.bin" \
    -P "parameters_J_${step}.bin" \
    -o "msa_energies_${step}.txt"
  taskset --cpu-list "$cpulist" plot_energy.py \
    -e "msa_energies_${step}.txt" \
    -e "MC_energies_${step}.txt" \
    -l "msa" \
    -l "mcmc" \
    -t "${title}, step ${step}" \
    -o "${name}_${slug}_energy_${step}.png"
  echo

  if [[ -v prev_step ]]; then
    echo "previous model comparison"
    plot_model_compare \
      -s "$prev_step" \
      -s "$step" \
      -l "step $prev_step" \
      -l "step $step" \
      -t "$title" -p -g -v
    echo

    echo "sequence energy comparisons"
    compute_energies \
      -n msa_numerical.txt \
      -p "parameters_h_${prev_step}.bin" \
      -P "parameters_J_${prev_step}.bin" \
      -o "msa_energies_${prev_step}.txt"

    taskset --cpu-list "$cpulist" plot_energy_compare.py \
      -e "msa_energies_${prev_step}.txt" \
      -e "msa_energies_${step}.txt" \
      -l "mcmc step $prev_step" \
      -l "msa step $step" \
      -t "${title}, step ${prev_step} vs step ${step}" \
      -o "${name}_${slug}_energy_${prev_step}-vs-${step}.png"
  fi
  echo
}

function get_step() {
  local STEP
  STEP=$(wc -l bmdca_run.log | cut -d" " -f1)
  echo $(( STEP - 1 ))
}

#
# Parse command line options
#

OPTIONS=t:d:s:n:
LONGOPTIONS=title:,description:,step:,nproc:
PARSED=$(getopt -o ${OPTIONS} --long ${LONGOPTIONS} -n "$0" -- "$@")
eval set -- "$PARSED"
while [ $# -ge 1 ]; do
  case "$1" in
    -t|--title)
      TITLE="${2}"
      shift 2
      ;;
    -d|--description)
      DESCRIPTION="${2}"
      shift 2
      ;;
    -s|--step)
      STEP="${2}"
      shift 2
      ;;
    -n|--nproc)
      NPROC="${2}"
      shift 2
      ;;
    --)
      shift
      break
      ;;
    *)
      show_error "Error: unknown command line option."
      print_usage
      exit 3
      ;;
  esac
done

if ! [[ -v STEP ]]; then
  STEP="$(get_step)"
  echo "plotting step $STEP"
fi

if ! [[ -v NPROC ]]; then
  NPROC=$(nproc)
fi

make_figures "$TITLE" "$DESCRIPTION" "$STEP" "$NPROC"
