#! /usr/bin/env python3
""" docstring """

import argparse
import os
import sys
import subprocess
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

import dcatools as tools

#  plt.rcParams["figure.figsize"] = [16, 12]
plt.rcParams.update({"mathtext.default": "regular"})


def parse_options():
    """ cli parser """
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-i",
        "--msa1",
        dest="msa1",
        required=False,
        default="",
        help="input msa 1",
    )
    parser.add_argument(
        "-I",
        "--msa2",
        dest="msa2",
        required=False,
        default="",
        help="input msa 2",
    )
    parser.add_argument(
        "-n",
        "--numeric_msa1",
        dest="num_msa1",
        default="",
        required=False,
        help="numeric msa 1",
    )
    parser.add_argument(
        "-N",
        "--numeric_msa2",
        dest="num_msa2",
        default="",
        required=False,
        help="numeric msa 2",
    )
    parser.add_argument(
        "-l",
        "--msa1_label",
        dest="msa1_label",
        required=True,
        help="msa 1 label",
    )
    parser.add_argument(
        "-L",
        "--msa2_label",
        dest="msa2_label",
        required=True,
        help="msa 2 label",
    )
    parser.add_argument(
        "-T", "--title", dest="title", required=True, help="title"
    )
    parser.add_argument(
        "-c",
        "--cleanup",
        dest="cleanup",
        action="store_true",
        default=False,
        help="delete intermediate files",
    )
    parser.add_argument(
        "-s",
        "--skip",
        dest="skip",
        action="store_true",
        default=False,
        help="skip processing and plot existing output",
    )
    parser.add_argument(
        "-r",
        "--reference_msa1",
        dest="ref1",
        help="reference sequence in msa 1 for comparison",
    )
    parser.add_argument(
        "-R",
        "--reference_msa2",
        dest="ref2",
        help="reference sequence in msa 2 for comparison",
    )
    return parser.parse_args()


def main():
    """ do stuff """
    options = parse_options()

    command = ["compare_distances"]

    if options.num_msa1:
        command.append("-n")
        command.append(options.num_msa1)
    elif options.msa1:
        command.append("-i")
        command.append(options.msa1)

    if options.num_msa2:
        command.append("-N")
        command.append(options.num_msa2)
    elif options.msa2:
        command.append("-I")
        command.append(options.msa2)
    if options.ref1 is not None:
        command.append("-r")
        command.append(options.ref1)
    if options.ref2 is not None:
        command.append("-R")
        command.append(options.ref2)

    if options.skip is False:
        res = subprocess.call(command)
        if res != 0:
            sys.exit(1)

    msa1_max_distances = tools.load_distances("msa1_max_similarity.txt")
    msa2_max_distances = tools.load_distances("msa2_max_similarity.txt")
    msa1_msa2_max_distances = tools.load_distances("msa1_msa2_max_similarity.txt")
    msa2_msa1_max_distances = tools.load_distances("msa2_msa1_max_similarity.txt")
    msa1_mean_distances = tools.load_distances("msa1_mean_similarity.txt")
    msa2_mean_distances = tools.load_distances("msa2_mean_similarity.txt")
    msa1_msa2_mean_distances = tools.load_distances("msa1_msa2_mean_similarity.txt")
    msa2_msa1_mean_distances = tools.load_distances("msa2_msa1_mean_similarity.txt")
    if options.ref1 is not None:
        msa1_ref1_max_distances = tools.load_distances(
            "msa1_msa1-ref" + options.ref1 + "_max_similarity.txt"
        )
        msa2_ref1_max_distances = tools.load_distances(
            "msa2_msa1-ref" + options.ref1 + "_max_similarity.txt"
        )
    if options.ref2 is not None:
        msa1_ref2_max_distances = tools.load_distances(
            "msa1_msa2-ref" + options.ref2 + "_max_similarity.txt"
        )
        msa2_ref2_max_distances = tools.load_distances(
            "msa2_msa2-ref" + options.ref2 + "_max_similarity.txt"
        )

    prefix = tools.slugify(options.title)
    slug1 = tools.slugify(options.msa1_label)
    slug2 = tools.slugify(options.msa2_label)
    if options.ref1 is not None:
        slug_ref1 = tools.slugify(
            options.msa1_label + " (Seq " + options.ref1 + ")"
        )
    if options.ref2 is not None:
        slug_ref2 = tools.slugify(
            options.msa2_label + " (Seq " + options.ref2 + ")"
        )

    if "_step_" in prefix:
        prefix1, prefix2 = prefix.split("_step_")
        outname = (
            prefix1
            + "_sequence_similarity_"
            + slug1
            + "_"
            + slug2
            + "_step_"
            + prefix2
            + ".png"
        )
        if options.ref1 is not None:
            outname_ref1 = (
                prefix1
                + "_similarity_reference_"
                + slug1
                + "_"
                + slug2
                + "_"
                + slug_ref1
                + "_step_"
                + prefix2
                + ".png"
            )
        if options.ref2 is not None:
            outname_ref2 = (
                prefix1
                + "_similarity_reference_"
                + slug1
                + "_"
                + slug2
                + "_"
                + slug_ref2
                + "_step_"
                + prefix2
                + ".png"
            )
    else:
        outname = (
            prefix + "_sequence_similarity_" + slug1 + "_" + slug2 + ".png"
        )
        if options.ref1 is not None:
            outname_ref1 = (
                prefix
                + "_similarity_reference_"
                + slug1
                + "_"
                + slug2
                + "_"
                + slug_ref1
                + ".png"
            )
        if options.ref2 is not None:
            outname_ref2 = (
                prefix
                + "_similarity_reference_"
                + slug1
                + "_"
                + slug2
                + "_"
                + slug_ref2
                + ".png"
            )

    subplots_count = 4
    if options.ref1 is not None:
        subplots_count = subplots_count + 1
    if options.ref2 is not None:
        subplots_count = subplots_count + 1

    if subplots_count > 4:
        subplots_rows = "3"
        plt.rcParams["figure.figsize"] = [16, 18]
    else:
        subplots_rows = "2"
        plt.rcParams["figure.figsize"] = [16, 12]
    subplots_columns = "2"

    with plt.style.context("fivethirtyeight"):
        fig = plt.figure()
        axes = fig.add_subplot(111)
        axes.tick_params(
            axis="both",
            which="both",
            labelcolor="none",
            top=False,
            bottom=False,
            left=False,
            right=False,
        )
        axes.grid(False)
        axes.set_title("Sequence Similarity: " + options.title, pad=45)
        axes.set_xlabel("Nearest Sequence Similarity")

        ax = fig.add_subplot(int(subplots_rows + subplots_columns + "1"))
        ax.set_title("Within-Group Max", fontsize=plt.rcParams["axes.labelsize"])
        ax.hist(
            msa1_max_distances,
            alpha=0.5,
            label=options.msa1_label,
            density=True,
            bins=20,
        )
        ax.hist(
            msa2_max_distances,
            alpha=0.5,
            label=options.msa2_label,
            density=True,
            bins=20,
        )
        ax.set_xlabel("")
        ax.set_ylabel("")
        ax.legend(loc="upper right")

        ax = fig.add_subplot(int(subplots_rows + subplots_columns + "3"), sharex=ax)
        ax.set_title("Within-Group Mean", fontsize=plt.rcParams["axes.labelsize"])
        ax.hist(
            msa1_mean_distances,
            alpha=0.5,
            label=options.msa1_label,
            density=True,
            bins=20,
        )
        ax.hist(
            msa2_mean_distances,
            alpha=0.5,
            label=options.msa2_label,
            density=True,
            bins=20,
        )
        ax.set_xlabel("")
        ax.set_ylabel("")
        ax.legend(loc="upper right")

        ax = fig.add_subplot(int(subplots_rows + subplots_columns + "2"))
        ax.set_title("Between-Group Max", fontsize=plt.rcParams["axes.labelsize"])
        ax.hist(
            msa1_msa2_max_distances,
            alpha=0.5,
            label=options.msa1_label + "-to-" + options.msa2_label,
            density=True,
            bins=20,
        )
        ax.hist(
            msa2_msa1_max_distances,
            alpha=0.5,
            label=options.msa2_label + "-to-" + options.msa1_label,
            density=True,
            bins=20,
        )
        ax.set_xlabel("")
        ax.set_ylabel("")
        ax.legend(loc="upper right")

        ax = fig.add_subplot(int(subplots_rows + subplots_columns + "4"), sharex=ax)
        ax.set_title("Between-Group Mean", fontsize=plt.rcParams["axes.labelsize"])
        ax.hist(
            msa1_msa2_mean_distances,
            alpha=0.5,
            label=options.msa1_label + "-to-" + options.msa2_label,
            density=True,
            bins=20,
        )
        ax.hist(
            msa2_msa1_mean_distances,
            alpha=0.5,
            label=options.msa2_label + "-to-" + options.msa1_label,
            density=True,
            bins=20,
        )
        ax.set_xlabel("")
        ax.set_ylabel("")
        ax.legend(loc="upper right")

        if options.ref1 is not None:
            ax = fig.add_subplot(int(subplots_rows + subplots_columns + "5"))
            ref_label = "Reference (" + options.msa1_label + ", " + "Seq " + options.ref1 + ")"
            ax.set_title(ref_label, fontsize=plt.rcParams["axes.labelsize"])

            ax.hist(
                msa1_ref1_max_distances,
                alpha=0.5,
                label=options.msa1_label
                + "-to-"
                + options.msa1_label
                + "-(seq "
                + options.ref1
                + ")",
                density=True,
                bins=20,
            )
            ax.hist(
                msa2_ref1_max_distances,
                alpha=0.5,
                label=options.msa2_label
                + "-to-"
                + options.msa1_label
                + "-(seq "
                + options.ref1
                + ")",
                density=True,
                bins=20,
            )
            ax.set_xlabel("")
            ax.set_ylabel("")
            ax.legend(loc="upper right")

        if options.ref2 is not None:
            if options.ref1 is not None:
                ax = fig.add_subplot(int(subplots_rows + subplots_columns + "6"))
            else:
                ax = fig.add_subplot(int(subplots_rows + subplots_columns + "5"))

            ref_label = "Reference (" + options.msa2_label + ", " + "Seq " + options.ref2 + ")"
            ax.set_title(ref_label, fontsize=plt.rcParams["axes.labelsize"])

            ax.hist(
                msa1_ref2_max_distances,
                alpha=0.5,
                label=options.msa1_label
                + "-to-"
                + options.msa1_label
                + "-(seq "
                + options.ref2
                + ")",
                density=True,
                bins=20,
            )
            ax.hist(
                msa2_ref2_max_distances,
                alpha=0.5,
                label=options.msa2_label
                + "-to-"
                + options.msa1_label
                + "-(seq "
                + options.ref2
                + ")",
                density=True,
                bins=20,
            )
            ax.set_xlabel("")
            ax.set_ylabel("")
            ax.legend(loc="upper right")

        fig.tight_layout()
        fig.savefig(outname)

    if options.cleanup:
        os.remove("msa1_max_similarity.txt")
        os.remove("msa2_max_similarity.txt")
        os.remove("msa1_msa2_max_similarity.txt")
        os.remove("msa2_msa1_max_similarity.txt")
        os.remove("msa1_mean_similarity.txt")
        os.remove("msa2_mean_similarity.txt")
        os.remove("msa1_msa2_mean_similarity.txt")
        os.remove("msa2_msa1_mean_similarity.txt")
        if options.ref1 is not None:
            os.remove("msa1_msa1-ref" + options.ref1 + "_max_similarity.txt")
            os.remove("msa2_msa1-ref" + options.ref1 + "_max_similarity.txt")
        if options.ref2 is not None:
            os.remove("msa1_msa2-ref" + options.ref2 + "_max_similarity.txt")
            os.remove("msa2_msa2-ref" + options.ref2 + "_max_similarity.txt")


if __name__ == "__main__":
    main()
