#! /usr/bin/env python3
""" docstring """

import argparse
import os
import sys
import numpy as np
import pandas as pd
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns

import dcatools as tools


def parse_options():
    """ cli parser """
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-i",
        "--input",
        dest="dms",
        required=True,
        help="input dms file",
    )
    return parser.parse_args()


def main():
    """ do stuff """
    options = parse_options()

    prefix = os.path.splitext((options.dms).replace("/", "_"))[0]
    outfile = prefix + ".png"

    data = pd.read_csv(options.dms, sep="\t", index_col=0)

    with plt.style.context("fivethirtyeight"):
        fig, ax = plt.subplots(figsize=(np.ceil(data.shape[1]/3), 6.5))
        ax = sns.heatmap(data, annot=False, cmap="bwr", center=0, square=True)
        ax.set_yticklabels(ax.get_yticklabels(), rotation=0)
        ax.set_xticklabels(ax.get_xticklabels(), rotation=45)
        plt.tight_layout()
        fig.savefig(outfile)
        plt.close()


if __name__ == "__main__":
    main()
